const stores=[
['绿洲','城市里的精神绿洲，给你最顶的派对氛围','落日飞车驶向绿洲站，抵达属于夜晚的音乐乌托邦。','1F'],
['INS TOWN','来魔法小镇赢下今晚的第一杯酒','坠入暮色小镇',''],
['HUSH','来自北京，听点纯正的嘻哈','末日战车加载完毕，带上你的Crew，开启午夜暴走模式！','3F'],
['upperwood','踩下复古专车的油门，对准UPPERWOOD的松弛入口，驶入霓虹与烟雾交织的都市幻夜。','落日余晖下，松弛与律动同频','2F'],
['RADI','一场蓄谋已久的「邂逅」。','循着低频声场驶入暗夜车站 把夜晚无限拉长',''],
['KZ','将纯粹的Live体验带进生活，Live.For This','踩下油门，奔赴现场，今夜每一首歌都是你的最佳配速。','2F'],
['CC','男孩的高能社交派对','油门踩死，对准时光隧道，带你驶入纸醉金迷的好莱坞午夜幻梦！','3F'],
['得体','这里真的太黑了，喜欢抓手指的嘉豪就别进来了','Sonic Ruins. 废墟声场',''],
['FRIENDS','FRIENDS是有一些无法解释的事情的抽象俱乐部。',"Let's偷吃",''],
['La fin','欧美流行音乐的快乐老家','Driving down with the sunset. 落日为伴，让LaFin陪你驶入夜幕','3F'],
['Jump','JUMP into 2016','复古超跑载着欧美流行，从落日开进JUMP的夜晚。','4F'],
['便利店','边吃边蹦边干杯，打碟打酒打咖啡','一辆移动的蹦迪购物车，自制一杯调酒，为今晚派对加点快乐补给！',''],
['INSHOST','','专属Cybertruck座驾把夜晚无限拉长，只管尽兴，管家自会接住一切。',''],
['INSLAND','','让落日飞车带着你一起去追一场属于音乐与城市的浪漫日落！','']];
const $ = id => document.getElementById(id);
const shuffle = input => { const a=[...input]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };
const escapeHTML = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SCORE_KEY='ins-lantern-scores-v2';
let deck=[],selected=[],matched=[],playing=false,locked=false,deadline=0,timer=null,turn=0,recommended=null;
let points=0,combo=0,comboPoints=0,attempts=0,lastSecond=61,player='游园客',currentResult=null;
let audioContext=null,soundOn=true,storageAvailable=true;
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
function readScores(){try{const raw=JSON.parse(localStorage.getItem(SCORE_KEY)||'[]');return Array.isArray(raw)?raw.filter(r=>r&&typeof r.name==='string'&&Number.isFinite(r.score)&&r.score>=0&&r.score<=2500&&typeof r.id==='string').slice(0,100):[];}catch{storageAvailable=false;return [];}}
let scores=readScores();
function art(id){return `<div class="art"><img src="assets/lanterns/${id}.png" alt="${stores[id][0]}花灯" draggable="false"></div>`;}
function initAudio(){if(!soundOn)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});}catch{soundOn=false;updateSound();}}
function beep(frequency=520,length=.11,volume=.06){if(!soundOn||!audioContext||audioContext.state!=='running'||document.hidden)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+length);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+length);}
function updateSound(){$('sound').textContent=soundOn?'声音：开':'声音：关';$('sound').setAttribute('aria-pressed',String(soundOn));}
function clearUrgency(){document.body.classList.remove('urgent-mode','last-three');$('countdown').classList.add('hidden');$('countdown').textContent='';$('time').classList.remove('urgent');}
function prepare(){turn++;clearInterval(timer);playing=false;locked=false;selected=[];matched=[];recommended=null;points=0;combo=0;comboPoints=0;attempts=0;lastSecond=61;currentResult=null;clearUrgency();
 const chosen=shuffle([...Array(12).keys()]).slice(0,6);deck=shuffle([...chosen,...chosen]);
 $('board').innerHTML=deck.map((id,i)=>`<button class="card tone-${id%6}" data-index="${i}" aria-label="第 ${i+1} 盏花灯，未翻开"><span class="back" aria-hidden="true"><i>✦</i><small>百戏游园</small><em>INS LAND</em></span>${art(id)}<span class="card-name">${stores[id][0]}</span></button>`).join('');
 $('count').textContent='0';$('progress').style.width='0%';$('time').textContent='01:00';$('live-score').textContent='0';$('combo').textContent='每对 +100';$('guide').disabled=true;$('guide').textContent='点亮花灯，解锁目的地';$('recommend-art').innerHTML=art(2);$('result-content').innerHTML='<span class="small-badge">花灯签 · 等待揭晓</span><h3>今晚，随光而行</h3><p>找到 6 对花灯，<br>让夜晚替你选一个目的地。</p>';$('message').textContent='翻开两盏花灯，寻找相同图案。';$('best').textContent=scores.length?Math.max(...scores.map(s=>s.score)):'—';
}
function start(){const name=$('player-name').value.trim();player=name.slice(0,12)||'游园客';if($('result-dialog').open)$('result-dialog').close();if($('modal').open)$('modal').close();prepare();initAudio();playing=true;deadline=Date.now()+60000;$('start-cover').classList.add('hidden');$('board').inert=false;timer=setInterval(tick,100);$('board').children[0].focus({preventScroll:true});}
function tick(){if(!playing)return;const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('time').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
 if(remaining<=10&&remaining>0){document.body.classList.add('urgent-mode');document.body.classList.toggle('last-three',remaining<=3);$('time').classList.add('urgent');$('countdown').classList.remove('hidden');$('countdown').textContent=remaining;if(lastSecond!==remaining){$('countdown').style.animation='none';void $('countdown').offsetWidth;$('countdown').style.animation='';beep(remaining<=3?880:640,.14,.09);if(remaining===10)$('message').textContent='最后 10 秒！抓紧点亮剩下的花灯。';}}
 lastSecond=remaining;if(remaining===0)finish(false);
}
function recordResult(won,remaining){const bonus=won?remaining*10:0;const score=points+bonus;const entry={id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),name:player,score,matched:matched.length,attempts,won,time:60-remaining,date:Date.now()};scores=storageAvailable?readScores():scores;const rank=1+scores.filter(s=>s.score>score).length;scores.push(entry);scores.sort((a,b)=>b.score-a.score||a.date-b.date);scores=scores.slice(0,100);try{localStorage.setItem(SCORE_KEY,JSON.stringify(scores));}catch{storageAvailable=false;}return {...entry,rank,bonus,base:matched.length*100,comboPoints};}
function finish(won){if(!playing)return;const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));playing=false;locked=true;clearInterval(timer);turn++;clearUrgency();$('board').inert=true;currentResult=recordResult(won,remaining);$('live-score').textContent=currentResult.score;$('best').textContent=Math.max(...scores.map(s=>s.score));
 if(matched.length){recommended=matched[Math.floor(Math.random()*matched.length)];const s=stores[recommended];$('recommend-art').innerHTML=art(recommended);$('result-content').innerHTML=`<span class="small-badge">${won?'全部点亮':'已点亮的相遇'} · 今晚的花灯签</span><h3>${s[0]}</h3><p>${s[1]}</p><span class="floor-inline">${s[3]?s[3]+' · 示意楼层':'楼层待确认'}</span>`;$('guide').disabled=false;$('guide').textContent='查看门店指引 →';}
 $('message').textContent=won?'✦ 所有花灯已点亮，今晚的目的地已揭晓。':`时间到！点亮 ${matched.length} 家门店，下一局继续。`;beep(won?780:240,.35,.07);showResult();
}
function rankRows(){return scores.slice(0,5).map((s,i)=>{const rank=1+scores.filter(r=>r.score>s.score).length;return `<li class="${currentResult?.id===s.id?'is-you':''}"><span class="rank-no">${String(rank).padStart(2,'0')}</span><span>${escapeHTML(s.name)}${currentResult?.id===s.id?'<small>本局</small>':''}</span><strong>${s.score}<em> 分</em></strong></li>`;}).join('');}
function showResult(){const r=currentResult;if(!r)return;$('result-body').innerHTML=`<div class="eyebrow">${r.won?'ALL LANTERNS LIT':'UNTIL WE MEET AGAIN'}</div><h2>${r.won?'花灯全亮，好运登场':'游园未尽，下局再会'}</h2><div class="final-score"><strong>${r.score}</strong><span>本局积分</span></div><div class="result-metrics"><div><strong>${r.matched}<em> / 6</em></strong><span>点亮门店</span></div><div><strong>${r.attempts?Math.round(r.matched/r.attempts*100):0}<em>%</em></strong><span>配对准确率</span></div><div><strong>${r.rank>100?'100+':r.rank}</strong><span>本机排名</span></div></div><div class="score-breakdown"><span>配对 ${r.base}</span><span>连击 ${r.comboPoints}</span><span>时间奖励 ${r.bonus}</span></div><div class="rank-heading"><h3>本机游园榜</h3><span>TOP 5 · 同分同名次</span></div><ol class="ranking">${rankRows()}</ol><p class="storage-note">${storageAvailable?'仅统计此浏览器保存的最高 100 条成绩，非全网排名。':'浏览器无法保存成绩，本局排名仅供本次会话参考。'}</p><div class="result-actions"><button class="primary" id="play-again">再挑战一次 ↻</button><button class="secondary" id="see-destination">${recommended!==null?'查看我的目的地 →':'逛逛全部门店 →'}</button></div>`;$('play-again').onclick=start;$('see-destination').onclick=()=>{$('result-dialog').close();recommended!==null?detail(recommended):directory();};$('result-dialog').showModal();}
function leaderboard(){$('modal-content').innerHTML=`<div class="eyebrow">LOCAL LEADERBOARD</div><h2>本机游园榜</h2><p class="muted">同一浏览器中的玩家成绩 · 同分同名次</p><ol class="ranking">${rankRows()||'<li class="empty-rank">还没有成绩，来点亮第一盏花灯吧。</li>'}</ol><p class="storage-note">榜单保存在当前设备的浏览器中，清除浏览器数据会清除榜单。</p>`;if(!$('modal').open)$('modal').showModal();}
$('board').onclick=e=>{const c=e.target.closest('.card');if(!c||!playing||locked)return;if(Date.now()>=deadline){tick();return;}const i=Number(c.dataset.index);if(selected.includes(i)||matched.includes(deck[i]))return;c.classList.add('face');c.setAttribute('aria-label',stores[deck[i]][0]+'花灯');beep(400+selected.length*80,.05,.025);selected.push(i);if(selected.length<2)return;locked=true;attempts++;const[a,b]=selected,epoch=turn;
 if(deck[a]===deck[b]){matched.push(deck[a]);combo++;const extra=Math.max(0,combo-1)*20;comboPoints+=extra;points+=100+extra;[a,b].forEach(n=>{const card=$('board').children[n];card.classList.add('matched');card.disabled=true;});$('count').textContent=matched.length;$('progress').style.width=matched.length/6*100+'%';$('live-score').textContent=points;$('combo').textContent=combo>1?`${combo} 连击 · +${100+extra}`:'配对成功 · +100';$('message').textContent=`点亮 ${stores[deck[a]][0]}！${combo>1?combo+' 连击，手感正好。':'继续寻找下一盏灯。'}`;beep(720,.12,.04);selected=[];locked=false;if(matched.length===6)finish(true);
 }else{combo=0;$('combo').textContent='连击中断 · 再试试';setTimeout(()=>{if(epoch!==turn)return;[a,b].forEach(n=>{const card=$('board').children[n];card.classList.remove('face');card.setAttribute('aria-label',`第 ${n+1} 盏花灯，未翻开`);});selected=[];locked=false;},750);}
};
function detail(id){const s=stores[id];$('modal-content').innerHTML=`<article class="detail"><div class="eyebrow">YOUR NEXT DESTINATION</div><h2>${s[0]}</h2>${id<12?`<div class="detail-art tone-${id%6}">${art(id)}</div>`:''}${s[1]?`<h4>关于门店</h4><p>${s[1]}</p>`:''}<h4>今晚的精彩</h4><p>${s[2]}</p><div class="floor">${s[3]?'楼层 · '+s[3]+'（示意）':'楼层 · 待确认'}<small>${s[3]?'楼层来自参考效果图，实际位置请以现场导视为准。':'当前资料未提供楼层，请向现场工作人员咨询。'}</small></div><button class="text-button" id="back-stores">← 查看全部门店</button></article>`;$('back-stores').onclick=directory;if(!$('modal').open)$('modal').showModal();}
function directory(){$('modal-content').innerHTML='<div class="eyebrow">FIND YOUR NIGHT</div><h2>每盏灯，都是一个目的地</h2><div class="store-grid">'+stores.map((s,i)=>`<button class="store-option" data-store="${i}">${i<12?art(i):'<span class="store-symbol">✦</span>'}<span>${s[0]}<small>${s[3]?s[3]+' · 示意楼层':'楼层待确认'} ↗</small></span></button>`).join('')+'</div>';$('modal-content').querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>detail(Number(b.dataset.store)));if(!$('modal').open)$('modal').showModal();}
$('start').onclick=start;$('restart').onclick=start;$('guide').onclick=()=>recommended!==null&&detail(recommended);$('directory').onclick=directory;$('rank-button').onclick=leaderboard;$('close').onclick=()=>$('modal').close();$('result-close').onclick=()=>$('result-dialog').close();$('sound').onclick=()=>{soundOn=!soundOn;if(soundOn)initAudio();updateSound();};$('result-dialog').addEventListener('close',()=>{$('restart').focus({preventScroll:true});});
$('mini-stores').innerHTML=[0,3,5,6,9,10].map(id=>`<button class="mini-store" data-store="${id}"><div class="mini-art tone-${id%6}">${art(id)}</div><span>${stores[id][0]}</span></button>`).join('');$('mini-stores').querySelectorAll('button').forEach(b=>b.onclick=()=>detail(Number(b.dataset.store)));
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&playing)tick();});prepare();$('board').inert=true;updateSound();
