const stores=[
['绿洲','城市里的精神绿洲，给你最顶的派对氛围','落日飞车驶向绿洲站，抵达属于夜晚的音乐乌托邦。','1F'],
['INS TOWN','来魔法小镇赢下今晚的第一杯酒','坠入暮色小镇',''],
['HUSH','来自北京，听点纯正的嘻哈','末日战车加载完毕，带上你的Crew，开启午夜暴走模式！','3F'],
['upperwood','踩下复古专车的油门，对准UPPERWOOD的松弛入口，驶入霓虹与烟雾交织的都市幻夜。','落日余晖下，松弛与律动同频','2F'],
['RADI','一场蓄谋已久的「邂逅」。','循着低频声场驶入暗夜车站 把夜晚无限拉长',''],
['KZ','将纯粹的Live体验带进生活，Live.For This','踩下油门，奔赴现场，今夜每一首歌都是你的最佳配速。','2F'],
['CC','男孩的高能社交派对','油门踩死，对准时光隧道，带你驶入纸醉金迷的好莱坞午夜幻梦！','3F'],
['得体','这里真的太黑了，喜欢抓手指的嘉豪就别进来了','Sonic Ruins. 废墟声场',''],
['FRIENDS','FRIENDS是有一些无法解释的事情的抽象俱乐部。',"Let's偷吃",''],
['La fin','欧美流行音乐的快乐老家','Driving down with the sunset. 落日为伴，让LaFin陪你驶入夜幕','3F'],
['Jump','JUMP into 2016','复古超跑载着欧美流行，从落日开进JUMP的夜晚。','4F'],
['便利店','边吃边蹦边干杯，打碟打酒打咖啡','一辆移动的蹦迪购物车，自制一杯调酒，为今晚派对加点快乐补给！',''],
['INSHOST','','专属Cybertruck座驾把夜晚无限拉长，只管尽兴，管家自会接住一切。',''],
['INSLAND','','让落日飞车带着你一起去追一场属于音乐与城市的浪漫日落！','']];
const $=id=>document.getElementById(id);const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function art(id){return `<div class="art" style="--col:${id%6};--row:${Math.floor(id/6)}"><img src="assets/lanterns.png" alt="${stores[id][0]}花灯" draggable="false"></div>`}
let deck=[],selected=[],matched=[],playing=false,locked=false,deadline=0,timer=null,turn=0,recommended=null;
function prepare(){turn++;clearInterval(timer);playing=false;locked=false;selected=[];matched=[];recommended=null;const chosen=shuffle([...Array(12).keys()]).slice(0,6);deck=shuffle([...chosen,...chosen]);$('board').innerHTML=deck.map((id,i)=>`<button class="card" data-index="${i}" aria-label="第 ${i+1} 盏花灯，未翻开"><span class="back" aria-hidden="true">✧</span>${art(id)}<span class="card-name">${stores[id][0]}</span></button>`).join('');$('count').textContent='0';$('progress').style.width='0%';$('time').textContent='01:00';$('time').classList.remove('urgent');$('start-cover').classList.remove('hidden');$('guide').disabled=true;$('guide').textContent='点亮花灯，解锁目的地';$('recommend-art').innerHTML=art(2);$('result-content').innerHTML='<span class="small-badge">等待点亮</span><h3>答案，藏在花灯里</h3><p>完成配对，让一盏花灯<br>带你走进今晚的精彩。</p>';$('message').textContent='准备好，寻找属于你的那盏灯。'}
function start(){prepare();playing=true;deadline=Date.now()+60000;$('start-cover').classList.add('hidden');$('message').textContent='翻开两盏花灯，寻找相同的图案。';timer=setInterval(tick,100)}
function tick(){if(!playing)return;const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('time').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('time').classList.toggle('urgent',remaining<=10);if(remaining===0)finish(false)}
function finish(won){playing=false;locked=true;clearInterval(timer);turn++;if(won){recommended=matched[Math.floor(Math.random()*matched.length)];const s=stores[recommended];$('recommend-art').innerHTML=art(recommended);$('result-content').innerHTML=`<span class="small-badge">全部点亮 · 今晚的花灯签</span><h3>${s[0]} ${s[3]?'· '+s[3]+'（示意）':''}</h3><p>${s[1]}</p>`;$('guide').disabled=false;$('guide').textContent='查看门店指引 →';$('message').textContent='✦ 6 对花灯全部点亮！今晚的目的地已揭晓。';if(matchMedia('(max-width:850px)').matches)$('recommend').scrollIntoView({behavior:'smooth',block:'center'});}else{$('message').textContent=`时间到！已点亮 ${matched.length} 家门店，再试一次吧。`;$('start-cover').innerHTML=`<span class="intro-star">✦</span><h2>还有花灯，等你点亮</h2><p>这次找到了 ${matched.length} / 6 对<br>再来一局，解锁今晚的目的地。</p><button class="primary" id="retry">再试一次 →</button>`;$('start-cover').classList.remove('hidden');$('retry').onclick=start;}}
$('board').onclick=e=>{const c=e.target.closest('.card');if(!c||!playing||locked)return;if(Date.now()>=deadline){tick();return}const i=Number(c.dataset.index);if(selected.includes(i)||matched.includes(deck[i]))return;c.classList.add('face');c.setAttribute('aria-label',stores[deck[i]][0]+'花灯');selected.push(i);if(selected.length<2)return;locked=true;const[a,b]=selected,epoch=turn;if(deck[a]===deck[b]){matched.push(deck[a]);[a,b].forEach(n=>{$('board').children[n].classList.add('matched');$('board').children[n].disabled=true});$('count').textContent=matched.length;$('progress').style.width=matched.length/6*100+'%';$('message').textContent=`点亮 ${stores[deck[a]][0]}！${matched.length===6?'全部找到了。':'继续寻找下一盏灯。'}`;selected=[];locked=false;if(matched.length===6)finish(true)}else{setTimeout(()=>{if(epoch!==turn)return;[a,b].forEach(n=>{const card=$('board').children[n];card.classList.remove('face');card.setAttribute('aria-label',`第 ${n+1} 盏花灯，未翻开`)});selected=[];locked=false},800)}};
function detail(id){const s=stores[id];$('modal-content').innerHTML=`<article class="detail"><div class="eyebrow">YOUR NEXT DESTINATION</div><h2>${s[0]}</h2>${id<12?`<div class="recommend-art">${art(id)}</div>`:''}${s[1]?`<h4>关于门店</h4><p>${s[1]}</p>`:''}<h4>今晚的精彩</h4><p>${s[2]}</p><div class="floor">${s[3]?'楼层 · '+s[3]+'（示意）':'楼层 · 待确认'}<small>${s[3]?'楼层来自参考效果图，实际位置请以现场导视为准。':'当前资料未提供楼层，请向现场工作人员咨询。'}</small></div><button class="text-button" id="back-stores">← 查看全部门店</button></article>`;$('back-stores').onclick=directory;if(!$('modal').open)$('modal').showModal()}
function directory(){$('modal-content').innerHTML='<div class="eyebrow">FIND YOUR NIGHT</div><h2>每一盏灯，都是一个目的地</h2><div class="store-grid">'+stores.map((s,i)=>`<button class="store-option" data-store="${i}">${s[0]}<span>${s[3]?s[3]+' · 示意楼层':'楼层待确认'} ↗</span></button>`).join('')+'</div>';$('modal-content').querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>detail(Number(b.dataset.store)));if(!$('modal').open)$('modal').showModal()}
$('start').onclick=start;$('restart').onclick=start;$('guide').onclick=()=>recommended!==null&&detail(recommended);$('directory').onclick=directory;$('close').onclick=()=>$('modal').close();$('modal').onclick=e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close()}};
$('mini-stores').innerHTML=[0,3,5,6,9,10].map(id=>`<button class="mini-store" data-store="${id}"><div class="mini-art">${art(id)}</div>${stores[id][0]}</button>`).join('');$('mini-stores').querySelectorAll('button').forEach(b=>b.onclick=()=>detail(Number(b.dataset.store)));prepare();
